services:
  - type: web
    name: leadway-cfo-dashboard
    runtime: static
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
